### ISSUE TITLE
upgrade to babel 6.0

### ISSUE THREAD

**Issue by delaneyj** [raquo/minimal-hapi-react-webpack#1]

**Comment by raquo** [comment]
I was waiting for https://github.com/gaearon/babel-plugin-react-transform/pull/50
Now that it has been addressed I've started work on this. I got almost everything to work, just need to resolve a couple issues with webpack config. ETA: this weekend.

**Comment by raquo** [comment]
All done. I'll release this tomorrow as 3.0
Also upgrading a bunch of other dependencies, including bumping React to 0.14
